[package]
name = "fenrix-dom"
version = "0.1.0"
edition = "2021"

[dependencies]
fenrix-core = { path = "../../crates/fenrix-core" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "Text",
    "Window",
]}