[package]
name = "fenrix"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "Main entry point for Fenrix: A modern Rust UI framework for building fast, reliable, and beautiful web apps."

[dependencies]
# Re-export core components
fenrix-core = { path = "../../crates/fenrix-core", version = "0.1.0"  }
fenrix-dom = { path = "../../crates/fenrix-dom", version = "0.1.0"  }
fenrix-macros = { path = "../../crates/fenrix-macros", version = "0.1.0"  }
fenrix-router = { path = "../../crates/fenrix-router", version = "0.1.0"  }

# Re-export for convenience
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["console", "MouseEvent", "Node"] }