[package]
name = "fenrix"
version = "0.1.0"
edition = "2021"

[dependencies]
# Re-export core components
fenrix-core = { path = "../../crates/fenrix-core" }
fenrix-dom = { path = "../../crates/fenrix-dom" }
fenrix-macros = { path = "../../crates/fenrix-macros" }
fenrix-router = { path = "../../crates/fenrix-router" }

# Re-export for convenience
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["console", "MouseEvent", "Node"] }